# Clase 1: Introducción a `python`
### Diplomado en Data Science UC 2022
---

Python es un lenguaje de programación usado en muchas áreas como desarrollo web, desarrollo de software, automatización de procesos, interacción con plataformas en la nube y como veremos ahora, en __Data Science__. 

Más de alguna vez hemos escuchado "¿`python` o `R` , cuál es mejor?", al final del día parte de la labor de un Data Scientist es elegir la herramienta correcta para el problema (y usuario) correcto.

**Python**

| Pros | Contras |
|------|---------|
| Sintaxis limpia | Single Thread por defecto |
| Multiparadigma (OOP, funcional, imperativa) | Implementaciones estadísticas (hay que buscarlas bien) |
| Lenguaje de programacion completo | Lenguaje interpretado |
| Lenguaje de alto nivel | Tipado fuerte |
| Transversal a muchas áreas (hay mucha comunidad) | |

**R**

| Pros | Contras |
|------|---------|
| Tidyverse | Single Thread por defecto |
| Pipe | Orientado a estadística |
| Implementaciones estadísticas | Lenguaje interpretado |
| Lenguaje de alto nivel | Paradigma de programación funcional |
| Reportería | |

Usaremos `python` durante el módulo de Machine Learning del diplomado, por lo que dedicaremos algunas semanas para aprender cómo transicionar los conocimientos adquiridos en `R`. 

## Entornos de trabajo populares en ciencias de datos.

### Jupyter Notebook

Link: <https://jupyter.org/>

Jupyter (abreviación de Julia, Python et R) es una herramienta que incorpora código y texto simultaneamente, similar a R Markdown. Cada celda puede ser de tipo **texto** (markdown) o **código** (ejemplo: julia, python o R). La capacidad de incorporar estas dos facetas convierte a los notebooks en una herramienta predilecta del Data Scientist. Para ser usado se debe tener una versión de python y jupyter instaladas ([recomendación para instalarlos](https://docs.anaconda.com/anaconda/install/index.html)). 


### Visual Studio Code

Link: <https://code.visualstudio.com/>

Al igual que RStudio, VS Code es un entorno de trabajo pensado para ser utilizado en muchos idiomas. Uno de los aspectos que lo hace muy popular son sus extensiones, que permiten añadir funcionalidades extras que faciliten nuestro trabajo. La extensión `Jupyter` permite trabajar con **Jupyter Notebooks** previa instalación de `python` y `jupyter` como se menciona arriba.

### Google Colab

Link: <https://colab.research.google.com/>


Consiste en un servicio gestionado en la nube por google de **Jupyter Notebooks**, al ser ejecutado mediante un servidor, no utiliza recursos de nuestro computador (ideal cuando usamos equipos con pocas capacidades o limitaciones para instalar software, como el computador del trabajo). Una alternativa muy parecida son los notebooks de [kaggle](https://www.kaggle.com/mpwolke/kaggle-notebook).

**Familiarización con el entorno**

Ejecutar una sola celda: `ctrl +  enter`

In [5]:
print("Bienvenidos al curso de Machine Learning")
# print("Esta es una celda de código")
print("Esta línea si se ejecuta. Ya no es un comentario")

Bienvenidos al curso de Machine Learning
Esta línea si se ejecuta. Ya no es un comentario


Recordemos las primeras operaciones que realizaron en `R` y su equivalencia en `python`

- Asignar Variables
```r
poleras <- c(254, 203, 182, 50)
meses   <- c("Ene", "Feb", "Mar", "Abr")
```


In [41]:
# Una variable almacena un valor:
dia_mes = 15
tienda  = "Jhonson's"
# Una lista almacena muchos valores a la vez
poleras = [254, 203, 182, 50]
meses   = ["Ene", "Feb", "Mar", "Abr"]

## Estructuras de control

`Python` a diferencia de `R` trabaja con indentación en vez de parentesis de llave para encapsular lo que está dentro de una estructura de control (ciclo, función, etc). La identación es un tabulador o 4 espacios sucesivos a la linea siguiente (enter) de la estructura de control. Es decir, algo que en `R` sería de la siguiente forma:

```r
if (condición) {
    acción
}
```
En `python` es:

```python
if condicion:
    acción
```
**¡Notar los 4 espacios debajo del if!**

In [40]:
nota = 3.5

if nota > 5.5:
    print("Eximido")
elif nota > 4.0:
    print("A dar examen")
else:
    print("A Salvar el ramo")

A Salvar el ramo


Los ciclos en `python` se caracterizan por tener una sintaxis un poco distinta, aunque intuitiva cuando uno se acostumbra. Tradicionalmente, uno definir un índice que recorre un conjunto de valores `for(i=0, i<n, i++)`. Python recibe 
- Una lista de valores sobre los que itera
- El nombre de una variable que irá recorriendo esa lista
- Las instrucciones que se deben ejecutar

In [44]:
print("Meses:", meses)

for mes in meses:
    print("Mes:", mes)

Meses: ['Ene', 'Feb', 'Mar', 'Abr']
Mes: Ene
Mes: Feb
Mes: Mar
Mes: Abr


### Listas por comprensión

Su principal objetivo es iterar sobre muchos valores de una lista, de manera más ordenada y corta. Buscaremos convertir el siguiente código:

In [66]:
colores = ["ROJO", "VERDE", "AZUL", "AMARILLO", "NARANJO"]

lista_auxiliar = []
for color in colores:
    lista_auxiliar.append(color.startswith("A"))

lista_auxiliar

[False, False, True, True, False]

Ahora con listas por comprensión:

In [70]:
comienza_con_A = [color.startswith("A") for color in colores]
comienza_con_A

[False, False, True, True, False]

Y si necesitamos ver solamente los colores que comiencen con "A", lo que es un filtro:

In [72]:
colores_A = [color for color in colores if color.startswith("A")]
colores_A

['AZUL', 'AMARILLO']

## Iteradores clásicos

Los iteradores son objetos cuyos valores aún no son generados, o sea contienen la información necesaria para producirlos cuando se utilice una estructura `for` o se le aplique la función `list` en el futuro. Esto es útil en términos de memoria. Por ejemplo, cuando cargamos 600,000 imágenes y aplicamos un filtro de colores, es conveniente cargar la foto, aplicar filtro, guardarla con el nuevo filtro a la vez y no todas al mismo tiempo.
Una vez que iteremos sobre el iterador, debemos definirlo nuevamente.

Algunas funciones que retornan iteradores son:

* `range(i, f, s)`: Crea una secuencia de datos desde `i` hasta `f` (este último no inclusivo con un salto `s`).
* `enumerate(lista)`: Retorna un iterador compuesta por tuplas que contienen el par `posición`, `elemento`.
* `zip(lista1, lista2)`: Retorna un iterador compuesto por tuplas que contienen elementos en la misma posición.

**Ejemplo range**


In [131]:
# Secuencia de valores desde el 2 hasta el 8 de salto 2.
secuencia = range(2, 9, 2)   
print(secuencia)

range(2, 9, 2)


El resultado es un iterador: para ver los valores, debemos aplicar la función `list` o un ciclo `for`. 

In [146]:
print(list(secuencia))

[2, 4, 6, 8]


In [144]:
secuencia = range(2, 9, 2)
for i in secuencia:
    print("Valor:", i)

Valor: 2
Valor: 4
Valor: 6
Valor: 8


**Ejemplo enumerate**

In [149]:
numero_y_mes = enumerate(meses)
list(numero_y_mes)

[(0, 'Ene'), (1, 'Feb'), (2, 'Mar'), (3, 'Abr')]

In [154]:
for num, mes in enumerate(meses): # destructuración
    print("Mes", num + 1, "es", mes)

Mes 1 es Ene
Mes 2 es Feb
Mes 3 es Mar
Mes 4 es Abr


**Ejemplo zip**

In [155]:
mes_y_poleras = zip(meses, poleras)
list(mes_y_poleras)

[('Ene', 254), ('Feb', 203), ('Mar', 182), ('Abr', 50)]

## Creación de funciones

Las funciones en python trabajan de manera similar a `R` a través del comando `def`

In [83]:
def fahrenheit_a_celcius(temperatura):
  calculo = (temperatura - 32) / 1.8
  return calculo

In [84]:
fahrenheit_a_celcius(3)

-16.11111111111111

Tampoco es necesario definir variables auxiliares:

In [89]:
def fahrenheit_a_celcius2(temperatura):
  return (temperatura - 32) / 1.8

fahrenheit_a_celcius2(3)

-16.11111111111111

Podemos usar funciones anónimas (o sea que definir su nombre es opcional). Su uso es dentro de otras estructuras con el fin usarlas de forma temporal, comunmente en la librería para análisis de datos `Pandas`.
Su estructura se define como:
```python
lambda parametro: función en terminos de parametro
```


In [90]:
fahrenheit_a_celcius3 = lambda temp: (temp - 32) / 1.8
fahrenheit_a_celcius3(3)

-16.11111111111111

**Ejemplo de aplicar una función dentro de listas por comprensión.**

Definir 

$$
f(x) = \left\{
\begin{array}{ll}
2x + 1  & x \leq 0  \\ x^2   & x > 0
\end{array} \right.
$$

In [79]:
f = lambda x: 2 * x + 1 if x <= 0 else x ** 2
valores = [4, -2, 9, 56, -67]
# aplicar a todos los valores
print([f(valor) for valor in valores])
# aplicar solo a los valores mayores a 5, en caso contrario no hacer nada
print([f(valor) if valor > 5 else valor for valor in valores])

[16, -3, 81, 3136, -133]
[4, -2, 81, 3136, -67]


## Librerías

Funcionan similar a R, las librerias son funciones que no vienen nativas en Python, pero pueden ser importadas (como los packages!)

Cuando importamos una libreria, le podemos asignar un alias. Por ejemplo: por convención se usa `np` para `numpy`.
Eventualmente podríamos usar cualquier nombre, pero se suele seguir la convención para facilidad de lectura de códigos y colaboración.

**Librerias que vamos a estudiar**
- `os`: Comunicación con sistema operativo.
- `NumPy`: Numeric Python (manipulacion de arrays)
- `Pandas`: Panel Data (análisis de datos) 
- `Scikit-Learn`: Machine Learning
- `Matplotlib`, `Seaborn`: Gráficos
- `SciPy`: Scientific Python (tiene un módulo de herramientas estadísticas)

**Complementarias**
- `plotly`, `holoviews`, `bokeh`, `altair`: gráficos interactivos.
- `pyjanitor`: limpieza de datos.
- `streamlit`, `dash`, `shiny` (en versión alpha): dashboards interactivos.
- `pingouin`: herramientas estadísticas.
- `statsmodels`: Modelos estadísticos como GLMs.
- `sktime`: modelos de series de tiempo.
- `mlxtend`, `yellowbrick`, `scikit-plot`, `feature-engine`: Herramientas complementarias de ML.
- `xgboost`, `catboost`, `lightgbm`: Métodos de árbol basados en boosting.
- `optuna`: métodos de búsqueda de parámetros para optimizar funciones.
- `h2o`: interfaz en python para H2O (framework de ML).
- `pycaret`: ML a alto nivel.
- `prince`: Reducción de dimencionalidad.
- `surprice`: sistemas de recomendación.
- `tensorflow`, `pytorch`: Deep Learning.

### NumPy

* Documentación: <https://numpy.org/doc/stable/>

Para poder trabajar con una lista de la forma que lo haciamos en algebra lineal, es necesario que usemos la libreria `numpy`, y transformemos nuestra lista en un vector, ya que en R podíamos mutiplicar un vector por un escalar sin problemas, en python las listas por defecto dejan de ser vectores:

In [12]:
print(poleras)
print(poleras * 2)

[100, 200, 305]
[100, 200, 305, 100, 200, 305]


La librería `numpy` implementa el *arreglo* y operaciones con conjuntos de datos.


In [7]:
import numpy as np

array_poleras = np.array(poleras)
array_poleras

array([100, 200, 305])

Ahora podemos utilizar nuestro array de manera lineal

In [8]:
array_poleras * 2

array([200, 400, 610])

Con esta librería logramos hacer la mayoria de los calculos que usualmente utilizaremos, que por defecto no hubiesemos podido, por ejemplo, este código dará error:

In [9]:
# Estas funciones no son nativas de python
log(5) + pi / sqrt(5) - exp(2)

NameError: name 'log' is not defined

Una forma de utilizar estas funciones es mediante sus respectivas implementaciones en NumPy.

In [10]:
np.log(5)

1.6094379124341003

Dicho esto, podemos solucionar el error.

In [11]:
np.log(5) + np.pi / np.sqrt(5) - np.exp(2)

-4.374655240288405

> **Nota**: Existe la posibilidad de seleccionar las funcionalidades que necesitamos de cierta librería. De esta forma, no es necesario mencionar la librería de procedencia. 

In [12]:
from numpy import log10 as mylog10

mylog10(1000)

3.0

**Manipulación de arrays**

Las operaciones entre listas se coercionarán usando la misma jerarquía que hemos aprendido en las clases de R.

In [32]:
print(poleras)
print(meses)
print(np.array(poleras + meses))

[100, 200, 305]
['Ene', 'Feb', 'Mar']
['100' '200' '305' 'Ene' 'Feb' 'Mar']


La selección de elementos se hace mediante índices **que parten desde cero y sin considerar el último elemento (!)** dentro de corchetes.

```python
lista = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(lista[0:2])
print(lista[2:4])
print(lista[4:6])
```

In [15]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [16]:
print(arr[0], arr[2:4], arr[-1])
print(arr[:3])

0 [2 3] 4
[0 1 2]


Otra forma de seleccionar datos es usando operaciones lógicas, mediante las que podemos extraer solo los datos que cumplan ciertos requisitos. Por ejemplo: creamos una población normalmente distribuida de estaturas, con media $\mu=160$ cm y desviación estándar $\sigma=5$ cm.

In [98]:
np.random.seed(2022)  # como set.seed de R, para reproducibilidad en NumPy
estaturas = np.random.normal(loc=160, scale=5, size=10000)
estaturas

array([159.9973605 , 158.62549288, 159.30357219, ..., 161.55546995,
       160.34955216, 158.77472458])

In [22]:
cond1 = estaturas > 159
cond2 = estaturas < 161

print(estaturas[(estaturas >= 159) & (estaturas <= 161)]) # Otros operadores: distinto != , no ~, o |
print(estaturas[cond1 & cond2])  ## Estas dos cosas son lo mismo

[159.45543558 159.6520132  160.29901162 ... 159.68858497 160.61774868
 159.5846869 ]
[159.45543558 159.6520132  160.29901162 ... 159.68858497 160.61774868
 159.5846869 ]


**Estadística descriptiva**


| Sintaxis	| Descripcion |
|-----------|-------------|
min() |	Minimo
max()	| Maximo
ptp()	| Rango
quantile(a, q)	| Cuantil q
median(a)	| Mediana
mean()	| Promedio
std()	| Desviacion Standard
var()	| Varianza

In [35]:
print("Promedio    :", np.mean(estaturas[estaturas > 175]))
print("Varianza    :", np.var(estaturas))
print("Percentil 75:", np.quantile(estaturas, 0.75))

Promedio    : 176.4725678217453
Varianza    : 24.987998190079143
Percentil 75: 163.49083520886546


**Vectorización**

Las funciones sobre arrays son aplicadas elemento a elemento, por lo que no necesitamos listas por comprensión: 

In [95]:
temperaturas_fahrenheit = np.array([32, 20, 62, 86])
fahrenheit_a_celcius(temperaturas_fahrenheit)


array([ 0.        , -6.66666667, 16.66666667, 30.        ])

**Control de valores en arrays**

Si deseamos asignar valores de acuerdo al cumplimiento de condiciones para un vector (similar a `ifelse` y `case_when` en R), las funciones `np.where` (ifelse) y `np.select` (case_when) son la solución, las cuales funcionan como:

```python
np.where(condicion, que hacer si es cierto, que hacer si es falso)
np.select(lista condiciones, lista elecciones, en otro caso)
```

In [52]:
notas = np.array([2.5, 7, 5.2, 1.4, 6.8, 5, 4.9, 5.8])
notas

array([2.5, 7. , 5.2, 1.4, 6.8, 5. , 4.9, 5.8])

In [50]:
# np.where
estado_aprobacion = np.where(notas >= 4, "Aprobado", "Reprobado")
estado_aprobacion

array(['Reprobado', 'Aprobado', 'Aprobado', 'Reprobado', 'Aprobado',
       'Aprobado', 'Aprobado', 'Aprobado'], dtype='<U9')

In [55]:
# np.select
estado_examen = np.select(
    # Condiciones
    condlist=[notas > 5.5, notas >= 4.0],
    # Elecciones
    choicelist=["Eximido", "A dar el examen"],
    # Else
    default="A salvar el ramo",
)

estado_examen

array(['A salvar el ramo', 'Eximido', 'A dar el examen',
       'A salvar el ramo', 'Eximido', 'A dar el examen',
       'A dar el examen', 'Eximido'], dtype='<U16')

**Manipulación de matrices**

Una matriz es simplemente un arreglo de arreglos y sus elementos se acceden usando 2 índices.

In [121]:
np.random.seed(2022)
mat = np.random.randint(low=0, high=10, size=(3, 4))

In [126]:
print("Una matriz:\n", mat)
print("Un elemento:", mat[1, 2])
print("Una fila:", mat[1, :])
print("Una columna:", mat[:, 1])
print("Un subconjunto:\n", mat[0:2, 1:4])

Una matriz:
 [[0 1 1 0]
 [7 8 2 8]
 [0 5 9 1]]
Un elemento: 2
Una fila: [7 8 2 8]
Una columna: [1 8 5]
Un subconjunto:
 [[1 1 0]
 [8 2 8]]


### Pandas

Es una librería cuya creación originalmente fue pensada para series de tiempo, sin embargo, hoy en día es la librería de python más popular para el análisis de datos. La conoceremos en profundidad en la **clase 3**.

In [113]:
import pandas as pd

data = {"meses": meses, "poleras": poleras} # Diccionario
df = pd.DataFrame(data)
df

meses  poleras
0   Ene      254
1   Feb      203
2   Mar      182
3   Abr       50

In [112]:
df["poleras"] * 2

0    508
1    406
2    364
3    100
Name: poleras, dtype: int64

> **Nota**: `pandas` trabaja con `numpy` por debajo, por ello entiende el trabajo matricial que realizamos.

### os

Por defecto un jupyter notebook usa como directorio el lugar donde se encuetra ubicado. Sin embargo, podemos obtener y cambiar el directorio de trabajo a nuestro gusto.

In [101]:
import os
os.getcwd()

'h:\\My Drive\\Universidad\\2022 - Diplomado Data Science\\clases-python\\01_intro-py'

In [103]:
ruta = "h:/My Drive/Universidad/2022 - Diplomado Data Science"
os.chdir(ruta)
os.getcwd()

'h:\\My Drive\\Universidad\\2022 - Diplomado Data Science'

Escribamos una tabla a `.csv`:

In [106]:
df.to_csv("datos.csv", index=False)

### Matplotlib

Es una librería para generar visualizaciones de datos. La veremos en profundidad en la **clase 3**.

La forma en que lo haciamos en `R`:

```r
plot(poleras)
barplot(poleras, names.arg = meses, main="Cantidad de poleas por mes")
```

En `python`:

In [120]:
from matplotlib import pyplot as plt

df.plot.bar()
plt.title("Cantidad de poleras por mes")
plt.xticks(ticks=range(4), labels=meses);

# Ejercicios

### 1) Tratamiento inicial:
Considere los siguientes datos de peso (en kilos) y altura (en centímetros) de 10 pacientes: 

In [157]:
pesos = [63, 72, 83, 54, 91, 53, 68, 89]
alturas = [152, 179, 170, 172, 169, 153, 161, 190]

   * a) Entregue el peso y las alturas de los primeros 4 pacientes.
   * b) Entregue el peso y las alturas de los últimos 3 pacientes.
   * c) Entregue el peso y las alturas de los 2 pacientes de al medio.
   * d) Calcule el promedio, varianza y desviación estándar de los pesos y las alturas de los pacientes.
   * e) Calcule el rango y el primer, segundo y tercer cuartil de los pesos y las alturas de los pacientes.
   * f) Defina una función que calcule el IMC para cada paciente (el IMC corresponde al peso (en kilos) dividido en la altura (en metros cuadrados)
   * g) En base a los IMC antes calculados, categorice cada paciente de modo que debajo de 18.5 indique Bajo peso, de 18.5 a 24.9 indique Normal, y en otro caso indique Sobrepeso/Obesidad.

In [ ]:
# Responda aquí


### 2) Datos simulados:
- a) Cree un conjunto de datos normalmente distribuidos, con media 100, desviacion estandard 10 y 150 elementos.
- b) Calcule el rango y el primer, segundo y tercer cuartil
- c) Elimine los elementos con valor mayor o igual a 120

In [ ]:
# Responda aquí


### 3) Funciones

Dado el siguiente vector:

In [ ]:
aux = [3.4121571, 5.4441121, 4.93843, 56.12314, 9.61124651, 32.653131113]

Utilice la función `round` a través de listas por comprensión para entregar el primer valor del vector `aux` redondeado a un número, el segundo valor de aux redondeado a dos números, el tercero a tres y así para todos los números de aux, es decir:

```python
[3.4, 5.44, 4.938, 56.1231, 9.61125, 32.653131]
```

In [175]:
# Responda aquí


## Soluciones Ejercicios

### 1)

In [ ]:
# 1a
print(pesos[:4])
print(alturas[:4])

[63, 72, 83, 54]
[152, 179, 170, 172]


In [ ]:
# 1b
print(pesos[-3:])
print(alturas[-3:])

[53, 68, 89]
[153, 161, 190]


In [ ]:
# 1c
print(pesos[3:5])
print(alturas[3:5])

[54, 91]
[172, 169]


In [ ]:
# 1d
print(f"Promedio pesos: {np.mean(pesos)}")
print(f"Desviación estándar pesos: {np.std(pesos)}")
print(f"Varianza pesos: {np.var(pesos)}")


print(f"Promedio alturas: {np.mean(alturas)}")
print(f"Desviación estándar alturas: {np.std(alturas)}")
print(f"Varianza alturas: {np.var(alturas)}")

Promedio pesos: 71.625
Desviación estándar pesos: 13.927827361078252
Varianza pesos: 193.984375
Promedio alturas: 168.25
Desviación estándar alturas: 12.018215341721914
Varianza alturas: 144.4375


In [ ]:
# 1e
print(f"Primer quartil pesos: {np.quantile(pesos, 0.25)}")
print(f"Segundo quartil pesos: {np.quantile(pesos, 0.5)}")
print(f"Tercer quartil pesos: {np.quantile(pesos, 0.75)}")
print(f"Rango pesos: {np.ptp(pesos)}")


print(f"Primer quartil alturas: {np.quantile(alturas, 0.25)}")
print(f"Segundo quartil alturas: {np.quantile(alturas, 0.5)}")
print(f"Tercer quartil alturas: {np.quantile(alturas, 0.75)}")
print(f"Rango alturas: {np.ptp(alturas)}")

Primer quartil pesos: 60.75
Segundo quartil pesos: 70.0
Tercer quartil pesos: 84.5
Rango pesos: 38
Primer quartil alturas: 159.0
Segundo quartil alturas: 169.5
Tercer quartil alturas: 173.75
Rango alturas: 38


In [166]:
# 1f
def IMC(a, b):
    return a / (b / 100) ** 2


result = [IMC(peso, altura) for peso, altura in zip(pesos, alturas)]
print(result)

[27.268005540166204, 22.47120876377142, 28.719723183391007, 18.25310978907518, 31.861629494765594, 22.64086462471699, 26.23355580417422, 24.653739612188367]


In [160]:
# 1g
pacientes = pd.DataFrame({"IMC": result})
pacientes

IMC
0  27.268006
1  22.471209
2  28.719723
3  18.253110
4  31.861629
5  22.640865
6  26.233556
7  24.653740

In [165]:
np.select(
    [pacientes["IMC"] < 18.5, pacientes["IMC"] <= 24.9],
    ["Bajo peso", "Normal"],
    "Sobrepeso/Obesidad"
)

array(['Sobrepeso/Obesidad', 'Normal', 'Sobrepeso/Obesidad', 'Bajo peso',
       'Sobrepeso/Obesidad', 'Normal', 'Sobrepeso/Obesidad', 'Normal'],
      dtype='<U18')

# 2) 

In [168]:
# 2a)
x = np.random.normal(loc=100, scale=10, size=150)

In [169]:
# 2b)
print(f"Primer quartil: {np.quantile(x, 0.25)}")
print(f"Segundo quartil: {np.quantile(x, 0.5)}")
print(f"Tercer quartil: {np.quantile(x, 0.75)}")
print(f"Rango: {np.ptp(x)}")

Primer quartil: 92.78740109078592
Segundo quartil: 99.95013759447104
Tercer quartil: 106.69940426420484
Rango: 57.33626680033191


In [176]:
# 2c)
print(x[x < 120])

[ 98.91087115 107.80058083  92.6652155  110.12733896  91.51211131
  95.96715076  82.96908964  91.96925191  99.3040264  100.59802325
 103.99577107 100.71587278  93.8991552  115.87712967 106.99627984
 101.11310414  98.36719828 100.05042111 105.71345837  88.34874589
 112.31737626  90.88790469  94.15051952 113.15534575 110.45607006
  96.25451916 118.31718821 118.79458427  85.64028161 103.65058812
 108.29477417  93.49433765 102.00776895  90.00176267 103.11818132
  94.89977059 105.22956793  97.15184425 106.65841396  92.07763633
 107.99570075  89.47132584  90.30178554  99.75057902  97.87840055
 103.01633336 103.2302113  109.20835026  91.46607798 115.72437571
  99.69092352 113.70891217 113.2743941   84.0773923   80.68081892
  95.82514728  93.32355667  91.99793063 101.03473216  81.75678936
  97.12911462  86.54650669 112.59414822  93.91054143  96.93075891
 110.99613303 110.2311851   89.75788911 105.17708663 106.7130677
  98.32877728 117.47306594  95.47642479 113.90612348 104.08159985
 110.642683

# 3)

In [174]:
# a
numeros = [3.4121571, 5.4441121, 4.93843, 56.12314, 9.61124651, 32.653131113]

resultado = [round(valor, redondeo + 1) for redondeo, 
             valor in enumerate(numeros)]

print(resultado)

[3.4, 5.44, 4.938, 56.1231, 9.61125, 32.653131]
